version: '2'

services:

  jenkins:
    image: h1kkan/jenkins-docker:lts 
    container_name: jenkins
    restart: unless-stopped 
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    links:
      - jenkins
    volumes:
      - "./nginx/conf.d/:/etc/nginx/conf.d/"
    environment:
      VIRTUAL_HOST: example.com
      HTTPS_METHOD: redirect
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: youremail@example.com

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
